spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/nursinghome
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: fjadsfdsoaingdosaingoseingodisnsoaeingoasidnoaidhgovduhreyqruyeqyfdsfoiagugfweg

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0f46caa576892c645d6f9a3eaaaabcd3
            client-secret: urUjkmTvwo54mCAfVoMVi5OxewWEbXuq
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
          naver:
            client-id: xKiz9QydtQ7ZTxuMdHn5
            client-secret: evKiQ4zTbF
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            scope: email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace